version: "3.9"
services:
  app:
    build: . #builds Dockerfile from current dir.
    ports:
      - "8080:8080" #maps host port to container.
    env_file:
      - .env #oads DB credentials & app config securely.
    depends_on: #makes sure Postgres starts first.
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
